-- chatbot_history: every message (incoming + outgoing) for dashboard and AI context
create table if not exists chatbot_history (
  id bigint generated by default as identity primary key,
  session_id text not null,
  message jsonb not null,
  customer jsonb not null,
  date_time timestamptz not null default now()
);

create index if not exists idx_chatbot_history_session_id on chatbot_history (session_id);
create index if not exists idx_chatbot_history_date_time on chatbot_history (date_time);

-- Enable Realtime for chatbot_history: In Supabase Dashboard go to Database > Replication
-- and add chatbot_history to the supabase_realtime publication (for INSERT events).

-- whatsapp_human_control: which conversations are in human takeover (AI must not reply)
create table if not exists whatsapp_human_control (
  session_id text primary key,
  is_human_controlled boolean not null,
  updated_at timestamptz default now()
);

comment on table chatbot_history is 'Stores every message (human and AI) for dashboard and AI context. message: { type: "human"|"ai", content: string }. customer: { number: string, name?: string }.';
comment on table whatsapp_human_control is 'When is_human_controlled = true, AI must not reply to that session.';
